# Generated by Django 6.0.1 on 2026-01-26 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClanQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('epic', 'Epic'), ('legendary', 'Legendary')], default='epic', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('required_progress', models.PositiveIntegerField(default=100)),
                ('total_progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(default='member', max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clans.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(db_index=True, default=0)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Leaderboard entry',
                'verbose_name_plural': 'Leaderboard entries',
                'ordering': ['-score', 'rank'],
                'indexes': [models.Index(fields=['-score'], name='clans_leade_score_16a017_idx'), models.Index(fields=['rank'], name='clans_leade_rank_e19e0a_idx')],
            },
        ),
    ]
