# Generated by Django 6.0.1 on 2026-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_allow_null_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clanquest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
