# Generated by Django 6.0.1 on 2026-01-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0008_add_clanquest_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanquest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='clanquest',
            name='deleted_by',
        ),
    ]
