# Generated by Django 6.0.1 on 2026-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0009_remove_clanquest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanquest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
