ARG NGINX_BASE=docker.io/library/nginx:alpine
FROM ${NGINX_BASE}
COPY frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
