ARG FRONTEND_BASE=ghcr.io/astral-sh/uv:python3.11-trixie-slim
FROM ${FRONTEND_BASE}

WORKDIR /srv/www

COPY frontend/dist /srv/www/dist
COPY frontend/serve_dist.py /srv/www/serve_dist.py

EXPOSE 80
CMD ["python", "/srv/www/serve_dist.py"]
