# Generated by Django 6.0.1 on 2026-01-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergoalprogress',
            name='goals_userprogress_updated_idx',
        ),
    ]
