# Generated by Django 6.0.1 on 2026-01-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailnotification',
            new_name='notificatio_schedul_eb2753_idx',
            old_name='notifications_email_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='emailnotification',
            new_name='notificatio_sent_4fd4db_idx',
            old_name='notifications_email_sent_idx',
        ),
    ]
