# Generated by Django 6.0.1 on 2026-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activities_activity_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activities_activitylog_created_at_idx',
        ),
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=10),
        ),
    ]
