# Generated by Django 6.0.1 on 2026-01-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_add_quest_state_fields'),
        ('activities', '0004_remove_activity_activities_activity_created_at_idx_and_more'),
    ]

    operations = [
    ]
