# Generated by Django 6.0.1 on 2026-01-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_add_custom_focuses_and_steps'),
        ('activities', '0005_merge_20260130_0602'),
    ]

    operations = [
    ]
