# Generated by Django 6.0.1 on 2026-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_merge_20260131_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='queststep',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=10),
        ),
    ]
